apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-go
  template:
    metadata:
      labels:
        app: server-go
    spec:
      containers:
      - name: server-go
        image: thenrique/server-go
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
