apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: thenrique/server-go
  newName: thenrique/server-go
  newTag: v1